cc_binary (
    name = "composite",
    srcs = [
        "composite.cc",
    ]
)

cc_binary (
    name = "decorator",
    srcs = [
        "decorator.cc",
    ]
)

cc_binary (
    name = "strategy_pattern",
    srcs = [
        "strategy_pattern.cc",
    ],
    copts = [
        "-std=c++20",
    ],
)
